### ISSUE TITLE
Inference with Noise-based models

### ISSUE THREAD

**Issue by rohitram96** [GU-DataLab/gdtm#1]
Hi @rchurch4,
Firstly, thanks for making the code for your topic models so readily accessible. 

**_Is there any way to perform inference (on a new set of documents) for the noise-based models?_** It seems that inference may be possible by using the mallet binaries directly, but is there any way to do this with the wrappers?

Kind Regards,
Rohit

**Comment by rchurch4** [comment]
Hi Rohit,

Thanks for taking the time to look into our models! I am traveling right now, but I promise to give you a more full answer when I return next week. For now, I can offer a quick answer and a glimmer of hope.

Technically, you can perform inference using the topic-noise models, however the process is convoluted and inefficient due to the existence of multiple distributions in the final trained model. Performing true inference on NLDA in terms of classifying documents using the topic-noise models is infeasible due to the fact that the end result is not a true probability distribution over the vocabulary. 

However, you can classify documents in a less formal way by taking into account the most likely words per topic when observing a document. We taken this approach in the past when working with election and pandemic data sets, and have found that the approach does reasonably well. 

I can give a more in-depth answer as to how you can do this when I return next week. If you think that classification will be a useful extension of the topic-noise models, I would be happy to add our approach to the package so that you and others can use it.

- Rob

**Comment by rohitram96** [comment]
Hi Rob,

Thanks for the quick response. 
This makes sense; I'll give the less formal approach a go on my dataset.

Cheers,
Rohit
